<div id="flags">
  <a href="<?php echo self::cms_set_locale_path('en', $route) ?>" class="tip_nw" original-title="<?php echo self::t('English') ?>"><img src="/images/system/en_flag.png" /></a>
  <a href="<?php echo self::cms_set_locale_path('sc', $route) ?>" class="tip_nw" original-title="<?php echo self::t('Simplified Chinese') ?>"><img src="/images/system/sc_flag.png" /></a>
  <a href="<?php echo self::cms_set_locale_path('tc', $route) ?>" class="tip_nw" original-title="<?php echo self::t('Traditional Chinese') ?>"><img src="/images/system/tc_flag.png" /></a>
</div>