<?php if (isset($attrs)) { unset($attrs['type']); } ?>
<label for="<?php self::p($attrs['id']) ?>"><?php self::p($label) ?></label>
<?php foreach ($options as $k => $v): ?>
<?php   if ($selected && $selected == $k) { $attrs['checked'] = 'checked'; } else { unset($attrs['checked']); } ?>
<input type="radio"<?php foreach ($attrs as $a => $av) { echo " $a=\"$av\""; } ?>/><?php echo $v ?><?php if (count($options) > 2): ?><br/><?php endif; ?>
<?php endforeach; ?>