<label for="<?php self::p($attrs['id']) ?>"><?php self::p($label) ?></label>
<?php if (isset($attrs['multiple'])): ?><br/><?php endif; ?>
<select<?php foreach ($attrs as $k => $v) { echo " $k=\"$v\""; } ?>>
  <?php if (isset($prompt_str)): ?>
  <option value=""><?php echo $prompt_str ?></option>  
  <?php endif; ?>  
  <?php foreach ($options as $k => $v): ?>
  <option value="<?php echo $k ?>"<?php if (isset($selected) && ((is_array($selected) && in_array($k, $selected)) || (!is_array($selected) && $selected == $k))) { echo ' selected="selected"'; } ?>><?php echo $v ?></option>  
  <?php endforeach; ?>
</select>